[2022-07-29 00:41:28,905] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.dag manual__2022-07-29T04:29:12.340433+00:00 [queued]>
[2022-07-29 00:41:28,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.dag manual__2022-07-29T04:29:12.340433+00:00 [queued]>
[2022-07-29 00:41:28,909] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 00:41:28,909] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-29 00:41:28,909] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 00:41:28,924] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): dag> on 2022-07-29 04:29:12.340433+00:00
[2022-07-29 00:41:28,925] {standard_task_runner.py:52} INFO - Started process 4114 to run task
[2022-07-29 00:41:28,927] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'dag', 'manual__2022-07-29T04:29:12.340433+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmphm9ijsct', '--error-file', '/tmp/tmp61j9b7zl']
[2022-07-29 00:41:28,927] {standard_task_runner.py:80} INFO - Job 66: Subtask dag
[2022-07-29 00:41:28,953] {task_command.py:370} INFO - Running <TaskInstance: my_dag.dag manual__2022-07-29T04:29:12.340433+00:00 [running]> on host DESKTOP-5GAFI6N.localdomain
[2022-07-29 00:41:28,998] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=dag
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T04:29:12.340433+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T04:29:12.340433+00:00
[2022-07-29 00:41:28,999] {logging_mixin.py:115} INFO - hi there!
[2022-07-29 00:41:28,999] {python.py:173} INFO - Done. Returned value was: None
[2022-07-29 00:41:29,003] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=dag, execution_date=20220729T042912, start_date=20220729T044128, end_date=20220729T044129
[2022-07-29 00:41:29,018] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-29 00:41:29,029] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
